import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function OrganizerRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed w-full pl-4 flex flex-row gap-4 bg-purple-800 text-purple-400 items-center h-[14vh]">
          <Link href="/">
            <div className="text-lg font-mono border-2 rounded border-green-400 bg-gradient-to-r hover:from-green-300 hover:to-purple-400 hover:text-purple-600 to-purple-800 from-green-600 text-green-300 hover:shadow-lg hover:-translate-y-1 p-1">
              Loyalty Harvest
            </div>
          </Link>
          <Link href="/user">
            <div className="text-lg font-mono border-2 rounded border-green-400 bg-gradient-to-r hover:from-green-300 hover:to-purple-400 hover:text-purple-600 to-purple-800 from-green-600 text-green-300 hover:shadow-lg hover:-translate-y-1 p-1">
              User Dashboard
            </div>
          </Link>
          <Link href="/user/createProof">
            <div className="text-lg font-mono border-2 rounded border-green-400 bg-gradient-to-r hover:from-green-300 hover:to-purple-400 hover:text-purple-600 to-purple-800 from-green-600 text-green-300 hover:shadow-lg hover:-translate-y-1 p-1">
              Create Proof
            </div>
          </Link>
          <Link href="/user/createSignature">
            <div className="text-lg font-mono border-2 rounded border-green-400 bg-gradient-to-r hover:from-green-300 hover:to-purple-400 hover:text-purple-600 to-purple-800 from-green-600 text-green-300 hover:shadow-lg hover:-translate-y-1 p-1">
              Create Signature
            </div>
          </Link>
          <Link href="/user/claim">
            <div className="text-lg font-mono border-2 rounded border-green-400 bg-gradient-to-r hover:from-green-300 hover:to-purple-400 hover:text-purple-600 to-purple-800 from-green-600 text-green-300 hover:shadow-lg hover:-translate-y-1 p-1">
              Claim
            </div>
          </Link>
          <div className="ml-32 p-1">
            <img src="icon.png" alt="Description of the image" />
          </div>
        </div>
        {children}
        <div className="bg-purple-900">Footer</div>
      </body>
    </html>
  );
}
