import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function OrganizerRootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="fixed w-full pl-4 flex flex-row gap-4 bg-purple-800 text-purple-400 items-center h-[14vh]">
          <Link href="/">
            <div className="text-lg font-semibold border-2 border-purple-600 bg-green-300 rounded hover:text-purple-300 hover:bg-green-500 hover:-translate-y-1 p-1">
              Loyalty Harvest
            </div>
          </Link>
          <Link href="/organizer">
            <div className="text-lg font-semibold border-2  border-purple-600 bg-green-300 rounded hover:text-purple-300 hover:bg-green-500 hover:-translate-y-1 p-1">
              Organizer Dashboard
            </div>
          </Link>
          <Link href="/organizer/createLeaves">
            <div className="text-lg font-semibold border-2  border-purple-600 bg-green-300 rounded hover:text-purple-300 hover:bg-green-500 hover:-translate-y-1 p-1">
              Create Leaves
            </div>
          </Link>
          <Link href="/organizer/createMerkle">
            <div className="text-lg font-semibold border-2  border-purple-600 bg-green-300 rounded hover:text-purple-300 hover:bg-green-500 hover:-translate-y-1 p-1">
              Create Merkle
            </div>
          </Link>
          <Link href="/organizer/createEvent">
            <div className="text-lg font-semibold border-2  border-purple-600 bg-green-300 rounded hover:text-purple-300 hover:bg-green-500 hover:-translate-y-1 p-1">
              Create Event
            </div>
          </Link>
          <Link href="/">
            <div className="text-lg font-semibold border-2 border-purple-600 bg-green-300 rounded hover:text-purple-300 hover:bg-green-500 hover:-translate-y-1 p-1">
              Placeholder
            </div>
          </Link>
          <Link href="/">
            <div className="text-lg font-semibold border-2 border-purple-600 bg-green-300 rounded hover:text-purple-300 hover:bg-green-500 hover:-translate-y-1 p-1">
              Placeholder
            </div>
          </Link>
        </div>
        {children}
        <div className="bg-purple-900">Footer</div>
      </body>
    </html>
  );
}
